import 'package:get/get.dart';

class AppLocalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      "appName": "Mind Cleanser",
      "tagline": "Trauma. Crisis. Cravings.",
      "oneSound": "One Sound. No more Fear.\nNo more Anger. No more Tears.",
      "skip": "Skip",
      "memories": "Sometimes memories won’t shift.\nSometimes cravings and stress feel too heavy.",
      "oneSoundHelps": "One sound helps you feel lighter, calmer, stronger.",
      "email": "Email",
      "enterEmail": "Enter your email",
      "password": "Password",
      "enterPassword": "Enter your password",
      "forgotPassword": "Forgot Password?",
      "login": "Log-in",
      "noAccount": "Don’t have an Account?",
      "signUp": "Sign Up",
      "firstName": "First Name",
      "enterFirstName": "Enter your first name",
      "lastName": "Last Name",
      "enterLastName": "Enter your last name",
      "congrats": "Congratulations",
      "accountCreated": "Your new account has been created successfully.",
      "continue": "Continue",
      "sessionGuide": "Session Guide",
      "goToHome": "Go to home",
      "forgotPasswordDesc": "Please, Enter your e-mail address below to receive your user and a new password.",
      "enterOTP": "Enter OTP",
      "otpSent": "We have just sent you 4 digit code via your email",
      "resendIn": "Resend code in {seconds} s",
      "noCode": "Didn’t receive code?",
      "resendCode": "Resend Code",
      "createNewPassword": "Create a New Password",
      "newPassword": "New Password",
      "enterNewPassword": "Enter new password",
      "confirmPassword": "Confirm Password",
      "confirmYourPassword": "Confirm your password",
      "passwordUpdated": "Your new password has been successfully.",
      "continueToLogin": "Continue to Log in",
      "onePurchase": "One purchase. Endless relaxation",
      "purchaseNow": "Purchase now",
      "note": "Note:",
      "sessionNote": "You may feel slightly tired after the session — rest for a few minutes if needed.",
      "treatments": "Treatments",
      "startSession": "Start Session",
      "quickReset": "Quick Reset (5 min)",
      "deepClean": "Deep Clean (20 min)",
      "nightSoothe": "Night Soothe (Continuous Play)",
      "affirmations": "Affirmations",
      "affirmationDesc": "Positive messages appear during and after sessions. You can revisit them anytime for motivation.",
      "purchaseInfo": "Purchase Info",
      "purchaseDesc": "One-time payment with local currency. Lifetime access and offline availability.",
      "visitWebsite": "Visit our website for help or updates.",
      "personalInfo": "Personal Info",
      "personalDetails": "Personal Details",
      "language": "Language",
      "shareWithFriends": "Share with Friends",
      "support": "Support",
      "aboutUs": "About Us",
      "privacyPolicy": "Privacy policy",
      "logOut": "Log Out",
      "accountDelete": "Account Delete",
      "editProfile": "Edit Profile",
      "aboutApp": "About the App",
      "appDesc": "Mind Cleanser uses therapeutic sound frequencies to help you relax, refocus, and restore mental calm.",
      "welcome": "Welcome to Mind Cleanser",
      "welcomeDesc": "Your personal sound therapy for peace and balance.",
      "purchaseOneTime": "Purchase One Time",
      "therapyTitle": "Mind Cleanser Sound Therapy",
      "therapyDesc": "Experience relaxation and focus through sound.\nOne-time purchase.\nNo subscription.",
      "whatYouGet": "What You’ll Get:\n\n- Unlimited lifetime access\n- All therapeutic sounds\n- Offline listening\n- Free future updates",
      "needHelp": "Need help? Visit our website",
      "appGuide": "App Guide",
      "session": "Session",
      "affirmativeQuote": "“The heart heals, not by forgetting, but by forgiving and moving forward”",
      "home": "Home",
      "guide": "Guide",
      "profile": "Profile"
    },
    'ar': {
      "appName": "منظف العقل",
      "tagline": "صدمة. أزمة. رغبة شديدة.",
      "oneSound":
          "صوت واحد.\nلا مزيد من الخوف.\nلا مزيد من الغضب.\nلا مزيد من الدموع.",
      "skip": "تخطى",
      "memories":
          "أحيانًا لا تتحرك الذكريات.\nأحيانًا تشعر الرغبات والتوتر بثقل كبير.",
      "oneSoundHelps": "صوت واحد يساعدك على الشعور بالخفة، الهدوء، والقوة.",
      "email": "البريد الإلكتروني",
      "enterEmail": "أدخل بريدك الإلكتروني",
      "password": "كلمة المرور",
      "enterPassword": "أدخل كلمة المرور",
      "forgotPassword": "هل نسيت كلمة المرور؟",
      "login": "تسجيل الدخول",
      "noAccount": "ليس لديك حساب؟",
      "signUp": "إنشاء حساب",
      "firstName": "الاسم الأول",
      "enterFirstName": "أدخل اسمك الأول",
      "lastName": "الاسم الأخير",
      "enterLastName": "أدخل اسمك الأخير",
      "congrats": "تهانينا",
      "accountCreated": "تم إنشاء حسابك الجديد بنجاح.",
      "continue": "متابعة",
      "sessionGuide": "دليل الجلسة",
      "goToHome": "الذهاب إلى الرئيسية",
      "forgotPasswordDesc":
          "من فضلك، أدخل عنوان بريدك الإلكتروني أدناه لتلقي اسم المستخدم وكلمة مرور جديدة.",
      "enterOTP": "أدخل رمز التحقق",
      "otpSent":
          "لقد أرسلنا لك للتو رمزًا مكونًا من 4 أرقام عبر بريدك الإلكتروني",
      "resendIn": "إعادة إرسال الرمز خلال {seconds} ث",
      "noCode": "لم تتلق الرمز؟",
      "resendCode": "إعادة إرسال الرمز",
      "createNewPassword": "إنشاء كلمة مرور جديدة",
      "newPassword": "كلمة المرور الجديدة",
      "enterNewPassword": "أدخل كلمة المرور الجديدة",
      "confirmPassword": "تأكيد كلمة المرور",
      "confirmYourPassword": "تأكيد كلمة المرور",
      "passwordUpdated": "تم تحديث كلمة المرور الجديدة بنجاح.",
      "continueToLogin": "متابعة لتسجيل الدخول",
      "onePurchase": "شراء واحد. استرخاء لا نهائي",
      "purchaseNow": "اشترِ الآن",
      "note": "ملاحظة:",
      "sessionNote":
          "قد تشعر بقليل من التعب بعد الجلسة — ارتح لبضع دقائق إذا لزم الأمر.",
      "treatments": "العلاجات",
      "startSession": "بدء الجلسة",
      "quickReset": "إعادة ضبط سريعة (5 دقائق)",
      "deepClean": "تنظيف عميق (20 دقيقة)",
      "nightSoothe": "تهدئة ليلية (تشغيل مستمر)",
      "affirmations": "تأكيدات إيجابية",
      "affirmationDesc":
          "تظهر رسائل إيجابية أثناء الجلسات وبعدها. يمكنك مراجعتها في أي وقت للتحفيز.",
      "purchaseInfo": "معلومات الشراء",
      "purchaseDesc":
          "دفعة واحدة بالعملة المحلية. وصول مدى الحياة وإمكانية الاستخدام دون اتصال.",
      "visitWebsite": "زور موقعنا للحصول على المساعدة أو التحديثات.",
      "personalInfo": "المعلومات الشخصية",
      "personalDetails": "التفاصيل الشخصية",
      "language": "اللغة",
      "shareWithFriends": "مشاركة مع الأصدقاء",
      "support": "الدعم",
      "aboutUs": "من نحن",
      "privacyPolicy": "سياسة الخصوصية",
      "logOut": "تسجيل الخروج",
      "accountDelete": "حذف الحساب",
      "editProfile": "تعديل الملف الشخصي",
      "aboutApp": "عن التطبيق",
      "appDesc":
          "يستخدم منظف العقل ترددات صوتية علاجية لمساعدتك على الاسترخاء، إعادة التركيز، واستعادة الهدوء العقلي.",
      "welcome": "مرحبًا بك في منظف العقل",
      "welcomeDesc": "علاجك الصوتي الشخصي للسلام والتوازن.",
      "purchaseOneTime": "شراء لمرة واحدة",
      "therapyTitle": "علاج منظف العقل الصوتي",
      "therapyDesc":
          "استمتع بالاسترخاء والتركيز من خلال الصوت.\nشراء لمرة واحدة.\nبدون اشتراك.",
      "whatYouGet":
          "ما ستحصل عليه:\n\n- وصول مدى الحياة غير محدود\n- جميع الأصوات العلاجية\n- الاستماع دون اتصال\n- تحديثات مجانية مستقبلية",
      "needHelp": "هل تحتاج إلى مساعدة؟ زور موقعنا",
      "appGuide": "دليل التطبيق",
      "session": "الجلسة",
      "affirmativeQuote":
          "“القلب يشفى، ليس بالنسيان، بل بالتسامح والمضي قدمًا”",
      "home": "الرئيسية",
      "guide": "الدليل",
      "profile": "الملف الشخصي",
    },
    'hi': {
      "appName": "माइंड क्लेंज़र",
      "tagline": "आघात। संकट। लालसा।",
      "oneSound":
          "एक ध्वनि।\nअब कोई डर नहीं।\nअब कोई क्रोध नहीं।\nअब कोई आँसू नहीं।",
      "skip": "छोड़ें",
      "memories":
          "कभी-कभी यादें हिलती नहीं।\nकभी-कभी लालसा और तनाव बहुत भारी लगते हैं।",
      "oneSoundHelps": "एक ध्वनि आपको हल्का, शांत और मजबूत महसूस कराती है।",
      "email": "ईमेल",
      "enterEmail": "अपना ईमेल दर्ज करें",
      "password": "पासवर्ड",
      "enterPassword": "अपना पासवर्ड दर्ज करें",
      "forgotPassword": "पासवर्ड भूल गए?",
      "login": "लॉग-इन",
      "noAccount": "खाता नहीं है?",
      "signUp": "साइन अप करें",
      "firstName": "पहला नाम",
      "enterFirstName": "अपना पहला नाम दर्ज करें",
      "lastName": "अंतिम नाम",
      "enterLastName": "अपना अंतिम नाम दर्ज करें",
      "congrats": "बधाई हो",
      "accountCreated": "आपका नया खाता सफलतापूर्वक बन गया है।",
      "continue": "जारी रखें",
      "sessionGuide": "सत्र मार्गदर्शिका",
      "goToHome": "होम पर जाएँ",
      "forgotPasswordDesc":
          "कृपया, अपना ईमेल पता नीचे दर्ज करें ताकि आपको उपयोगकर्ता नाम और नया पासवर्ड प्राप्त हो।",
      "enterOTP": "OTP दर्ज करें",
      "otpSent": "हमने अभी आपके ईमेल पर 4 अंकों का कोड भेजा है",
      "resendIn": "{seconds} सेकंड में कोड पुनः भेजें",
      "noCode": "कोड प्राप्त नहीं हुआ?",
      "resendCode": "कोड पुनः भेजें",
      "createNewPassword": "नया पासवर्ड बनाएँ",
      "newPassword": "नया पासवर्ड",
      "enterNewPassword": "नया पासवर्ड दर्ज करें",
      "confirmPassword": "पासवर्ड की पुष्टि करें",
      "confirmYourPassword": "अपने पासवर्ड की पुष्टि करें",
      "passwordUpdated": "आपका नया पासवर्ड सफलतापूर्वक अपडेट हो गया है।",
      "continueToLogin": "लॉगिन करने के लिए जारी रखें",
      "onePurchase": "एक खरीदारी। अनंत विश्राम",
      "purchaseNow": "अभी खरीदें",
      "note": "नोट:",
      "sessionNote":
          "सत्र के बाद आपको थोड़ी थकान महसूस हो सकती है — आवश्यकता हो तो कुछ मिनट आराम करें।",
      "treatments": "उपचार",
      "startSession": "सत्र शुरू करें",
      "quickReset": "त्वरित रीसेट (5 मिनट)",
      "deepClean": "गहरा सफाई (20 मिनट)",
      "nightSoothe": "रात्रि शांति (निरंतर चलन)",
      "affirmations": "सकारात्मक संदेश",
      "affirmationDesc":
          "सत्र के दौरान और बाद में सकारात्मक संदेश दिखाई देते हैं। आप इन्हें प्रेरणा के लिए कभी भी देख सकते हैं।",
      "purchaseInfo": "खरीदारी की जानकारी",
      "purchaseDesc":
          "स्थानीय मुद्रा में एक बार का भुगतान। आजीवन पहुँच और ऑफ़लाइन उपलब्धता।",
      "visitWebsite": "मदद या अपडेट के लिए हमारी वेबसाइट पर जाएँ।",
      "personalInfo": "व्यक्तिगत जानकारी",
      "personalDetails": "व्यक्तिगत विवरण",
      "language": "भाषा",
      "shareWithFriends": "दोस्तों के साथ साझा करें",
      "support": "सहायता",
      "aboutUs": "हमारे बारे में",
      "privacyPolicy": "गोपनीयता नीति",
      "logOut": "लॉग आउट",
      "accountDelete": "खाता हटाएँ",
      "editProfile": "प्रोफ़ाइल संपादित करें",
      "aboutApp": "ऐप के बारे में",
      "appDesc":
          "माइंड क्लेंज़र चिकित्सीय ध्वनि आवृत्तियों का उपयोग करता है जो आपको आराम, पुनः केंद्रित करने और मानसिक शांति बहाल करने में मदद करता है।",
      "welcome": "माइंड क्लेंज़र में आपका स्वागत है",
      "welcomeDesc": "शांति और संतुलन के लिए आपका व्यक्तिगत ध्वनि चिकित्सा।",
      "purchaseOneTime": "एक बार खरीदें",
      "therapyTitle": "माइंड क्लेंज़र ध्वनि चिकित्सा",
      "therapyDesc":
          "ध्वनि के माध्यम से विश्राम और ध्यान का अनुभव करें।\nएक बार खरीदारी।\nकोई सदस्यता नहीं।",
      "whatYouGet":
          "आपको क्या मिलेगा:\n\n- असीमित आजीवन पहुँच\n- सभी चिकित्सीय ध्वनियाँ\n- ऑफ़लाइन सुनने की सुविधा\n- भविष्य में मुफ़्त अपडेट",
      "needHelp": "मदद चाहिए? हमारी वेबसाइट पर जाएँ",
      "appGuide": "ऐप मार्गदर्शिका",
      "session": "सत्र",
      "affirmativeQuote":
          "“दिल ठीक होता है, भूलकर नहीं, बल्कि माफ़ करके और आगे बढ़कर”",
      "home": "होम",
      "guide": "मार्गदर्शिका",
      "profile": "प्रोफ़ाइल",
    },
    'zh': {
      "appName": "心灵净化",
      "tagline": "创伤。危机。渴望。",
      "oneSound": "一种声音。\n不再恐惧。\n不再愤怒。\n不再泪水。",
      "skip": "跳过",
      "memories": "有时记忆无法释怀。\n有时渴望和压力太过沉重。",
      "oneSoundHelps": "一种声音让你感到更轻松、更平静、更强大。",
      "email": "邮箱",
      "enterEmail": "输入您的邮箱",
      "password": "密码",
      "enterPassword": "输入您的密码",
      "forgotPassword": "忘记密码？",
      "login": "登录",
      "noAccount": "没有账户？",
      "signUp": "注册",
      "firstName": "名字",
      "enterFirstName": "输入您的名字",
      "lastName": "姓氏",
      "enterLastName": "输入您的姓氏",
      "congrats": "恭喜",
      "accountCreated": "您的新账户已成功创建。",
      "continue": "继续",
      "sessionGuide": "会话指南",
      "goToHome": "返回首页",
      "forgotPasswordDesc": "请在下方输入您的电子邮箱，以接收用户名和新密码。",
      "enterOTP": "输入验证码",
      "otpSent": "我们已通过您的邮箱发送了4位验证码",
      "resendIn": "{seconds}秒后重新发送",
      "noCode": "未收到验证码？",
      "resendCode": "重新发送验证码",
      "createNewPassword": "创建新密码",
      "newPassword": "新密码",
      "enterNewPassword": "输入新密码",
      "confirmPassword": "确认密码",
      "confirmYourPassword": "确认您的密码",
      "passwordUpdated": "您的新密码已成功更新。",
      "continueToLogin": "继续登录",
      "onePurchase": "一次购买。无限放松",
      "purchaseNow": "立即购买",
      "note": "注意：",
      "sessionNote": "会话后您可能会感到轻微疲劳 — 如有需要，请休息几分钟。",
      "treatments": "疗法",
      "startSession": "开始会话",
      "quickReset": "快速重置 (5分钟)",
      "deepClean": "深度清洁 (20分钟)",
      "nightSoothe": "夜间舒缓 (连续播放)",
      "affirmations": "肯定语",
      "affirmationDesc": "在会话期间及之后会出现积极信息。您可以随时重温以获得动力。",
      "purchaseInfo": "购买信息",
      "purchaseDesc": "使用本地货币一次性支付。终身访问和离线可用。",
      "visitWebsite": "访问我们的网站获取帮助或更新。",
      "personalInfo": "个人信息",
      "personalDetails": "个人资料",
      "language": "语言",
      "shareWithFriends": "与朋友分享",
      "support": "支持",
      "aboutUs": "关于我们",
      "privacyPolicy": "隐私政策",
      "logOut": "退出登录",
      "accountDelete": "删除账户",
      "editProfile": "编辑个人资料",
      "aboutApp": "关于应用",
      "appDesc": "心灵净化使用治疗性声音频率帮助您放松、重新聚焦并恢复内心平静。",
      "welcome": "欢迎来到心灵净化",
      "welcomeDesc": "为您带来平静与平衡的个人声音疗法。",
      "purchaseOneTime": "一次性购买",
      "therapyTitle": "心灵净化声音疗法",
      "therapyDesc": "通过声音体验放松与专注。\n一次性购买。\n无需订阅。",
      "whatYouGet": "您将获得：\n\n- 无限终身访问\n- 所有治疗声音\n- 离线收听\n- 未来免费更新",
      "needHelp": "需要帮助？访问我们的网站",
      "appGuide": "应用指南",
      "session": "会话",
      "affirmativeQuote": "“心灵的疗愈，不是通过遗忘，而是通过宽恕和向前迈进”",
      "home": "首页",
      "guide": "指南",
      "profile": "个人资料",
    },
  };
}
